#![forbid(unsafe_code)]

pub mod adversarial_fixtures;
pub mod capability_gap;
pub mod capture;
pub mod cli;
pub mod composition_semantics;
pub mod corpus;
pub mod doctor;
pub mod effect_canonical;
pub mod error;
pub mod fixture_taxonomy;
pub mod gap_triage;
pub mod harness;
pub mod import;
pub mod intent_inference;
pub mod ir_explainer;
pub mod ir_normalize;
pub mod ir_versioning;
pub mod keyseq;
pub mod lowering;
pub mod mapping_atlas;
pub mod migration_ir;
pub mod module_graph;
pub mod profile;
pub mod redact;
pub mod report;
pub mod runmeta;
pub mod sandbox;
pub mod seed;
pub mod semantic_contract;
pub mod state_effects;
pub mod state_event_translator;
pub mod style_semantics;
pub mod style_translator;
pub mod suite;
pub mod tape;
pub mod trace;
pub mod translation_planner;
pub mod tsx_parser;
pub mod util;
pub mod view_layout_translator;

pub use cli::run_from_env;
pub use error::{DoctorError, Result};
